name: single-cell-vae
channels:
  - defaults
dependencies:
  - torchaudio==0.7.2
  - torchvision==0.8.2
  - cudatoolkit=11.0
  - pytorch==1.7.1
  - black
  - flake8
  - pytorch-lightning
  - scikit-image
  - pylint
  - ipython
  - ipykernel